### PR TITLE
[Investigation] authentication + authroization service

### PR DESCRIPTION
**Pull request by yangxvlin**
A simple demonstration of using React.js + Keycloak + Springboot/StringSecurity to build a client_application + auth_server + resource_server system.

### CODE REVIEW

**Comment by free-y** [comment]
Will you copy your source code to here?

**Comment by yangxvlin** [comment]
It is just a simple demo. If it is worth exploring, I will implement one based on this example + social sign in in this repo.

**Comment by free-y** [comment]
> It is just a simple demo. If it is worth exploring, I will implement one based on this example + social sign in in this repo.

It's ok to put your demo into the investigation folder.

**Comment by yangxvlin** [comment]
I will migrate it to the folder

**Comment by free-y** [comment]
Two months no update, let's close it temporarily. we can reopen it if needed.

**Pull request closed without merging**
